version: '3'
services:
  codenames-server:
    environment: 
      - NODE_ENV=production
      # If you want to use a cloud service like Mongo Atlas, change this to your connection string,
      # or remove this like and store the connection string in a .env file so you don't have to commit it
      - MONO_DB_CONNECTION_STRING=mongodb://cndb:27017/codenames-prod
    env_file:
      - .env
    build:
      context: ./
    image: codenames-server
    ports:
     - "4000:4000"
    depends_on:
      - cndb

  # Runs MongoDB locally - If you want to use a cloud service you can remove from here down
  # If the cloud service isn't locally networked it's really slow, that's why I added local MongoDB
  cndb:
    image: mongo:4.2
    logging:
      driver: none