version: '3'
services:
  codenames-server:
    environment: 
      - NODE_ENV=production
      - MONO_DB_CONNECTION_STRING=mongodb://localhost:27017/codenames-prod
    env_file:
      - .env
    build:
      context: ./
    image: codenames-server
    ports:
     - "4000:4000"

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    logging:
      driver: none