version: '3.7'
services:
  codenames-server:
    environment: 
      - NODE_ENV=production
      # If you want to use a cloud service like Mongo Atlas, change this to your connection string,
      # or remove this like and store the connection string in a .env file so you don't have to commit it
      - MONO_DB_CONNECTION_STRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@cndb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    env_file:
      - .env
    build:
      context: ./
    image: codenames-server
    ports:
     - "4000:4000"
    depends_on:
      - cndb
    networks:
      - app-network

  # Runs MongoDB locally - If you want to use a cloud service you can remove from here down
  # If the cloud service isn't locally networked it's really slow, that's why I added local MongoDB
  cndb:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network   
    logging:
      driver: none

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge